services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retires: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_PW}
      - POSTGRES_DB=${POSTGRES_DB}  # this is optional
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
 
volumes:
  pg-data:
