services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
 
volumes:
  pg-data:
